import { useState } from 'react'
import { CalendarCheck, Check, Clock3, MapPin, Plus, Stethoscope, Trash2, X } from 'lucide-react'
import HealthHeader from '../components/HealthHeader'
import { useHealth } from '../context/HealthContext'
import { usePlatform } from '../../../context/PlatformContext'
import { completeAppointment, createAppointment, deleteAppointment } from '../services/health'
import { todayKey } from '../utils/dates'

const TODAY = todayKey
const dayDifference = (date) => Math.ceil((new Date(`${date}T12:00:00`) - new Date(`${TODAY}T12:00:00`)) / 86400000)

export default function AppointmentsPage() {
  const { appointments, healthOwnerId } = useHealth()
  const { notify } = usePlatform()
  const [showForm, setShowForm] = useState(false)
  const [form, setForm] = useState({ doctor: '', specialty: '', location: '', date: '', time: '', recurrenceMonths: 3, reminderDays: 14, note: '' })
  const save = async (event) => { event.preventDefault(); try { await createAppointment(healthOwnerId, form); setShowForm(false); setForm({ doctor: '', specialty: '', location: '', date: '', time: '', recurrenceMonths: 3, reminderDays: 14, note: '' }); notify('Rendez-vous ajouté.') } catch { notify('Impossible d’ajouter ce rendez-vous.') } }

  return <main className="mx-auto min-h-dvh w-full max-w-2xl px-4 pb-28 pt-6 sm:px-6"><HealthHeader title="Rendez-vous" subtitle="Médecins, analyses et contrôles" />
    <button type="button" onClick={() => setShowForm(true)} className="flex min-h-14 w-full items-center justify-center gap-2 rounded-2xl bg-violet-600 font-black text-white shadow-lg"><Plus /> Nouveau rendez-vous</button>
    <section className="mt-5 space-y-3">{appointments.map((item) => { const days = dayDifference(item.date); const soon = days >= 0 && days <= item.reminderDays; return <article key={item.id} className={`rounded-[1.5rem] border-2 bg-surface p-5 shadow-sm ${soon ? 'border-violet-300 dark:border-violet-800' : 'border-transparent'}`}><div className="flex items-start gap-3"><span className={`grid h-12 w-12 shrink-0 place-items-center rounded-2xl ${soon ? 'bg-violet-600 text-white' : 'bg-violet-50 text-violet-600 dark:bg-violet-950/30'}`}><Stethoscope /></span><span className="min-w-0 flex-1"><strong className="block text-lg">{item.doctor}</strong><small className="text-muted">{item.specialty || 'Consultation'}</small></span>{soon && <span className="rounded-full bg-violet-100 px-2.5 py-1 text-[10px] font-black text-violet-700">{days === 0 ? 'Aujourd’hui' : `Dans ${days} j`}</span>}</div><div className="mt-4 grid gap-2 text-sm text-muted sm:grid-cols-2"><span className="flex items-center gap-2"><CalendarCheck size={16} />{new Date(`${item.date}T12:00:00`).toLocaleDateString('fr-FR', { day: 'numeric', month: 'long', year: 'numeric' })}</span><span className="flex items-center gap-2"><Clock3 size={16} />{item.time || 'Heure à préciser'}</span>{item.location && <span className="flex items-center gap-2"><MapPin size={16} />{item.location}</span>}<span>Rappel {item.reminderDays} jours avant</span></div><div className="mt-4 grid grid-cols-[1fr_auto] gap-2"><button type="button" onClick={() => completeAppointment(healthOwnerId, item).then(() => notify(item.recurrenceMonths ? `Prochain RDV décalé de ${item.recurrenceMonths} mois.` : 'Rendez-vous terminé.')).catch(() => notify('Mise à jour impossible.'))} className="flex min-h-11 items-center justify-center gap-2 rounded-xl bg-emerald-500 text-sm font-black text-white"><Check size={18} /> Marquer terminé</button><button type="button" onClick={() => { if (window.confirm('Supprimer ce rendez-vous ?')) deleteAppointment(healthOwnerId, item.id).catch(() => notify('Suppression impossible.')) }} className="grid h-11 w-11 place-items-center rounded-xl bg-red-50 text-red-600 dark:bg-red-950/30"><Trash2 size={17} /></button></div></article> })}{!appointments.length && <div className="rounded-[2rem] border border-dashed border-slate-300 py-14 text-center dark:border-slate-700"><CalendarCheck className="mx-auto text-violet-400" size={38} /><h2 className="mt-3 text-xl font-black">Aucun rendez-vous</h2><p className="mt-1 text-sm text-muted">Ajoutez votre diabétologue, ophtalmo ou prise de sang.</p></div>}</section>
    {showForm && <div className="fixed inset-0 z-50 flex items-end justify-center"><button type="button" onClick={() => setShowForm(false)} className="absolute inset-0 bg-slate-950/50" aria-label="Fermer" /><form onSubmit={save} className="relative max-h-[92dvh] w-full max-w-lg overflow-y-auto rounded-t-[2rem] bg-surface p-5 pb-[max(1.5rem,env(safe-area-inset-bottom))]"><div className="flex items-center justify-between"><h2 className="text-xl font-black">Nouveau rendez-vous</h2><button type="button" onClick={() => setShowForm(false)}><X /></button></div><label className="mt-5 block text-sm font-black">Médecin / laboratoire<input value={form.doctor} onChange={(event) => setForm((value) => ({ ...value, doctor: event.target.value }))} className="field-input mt-2" placeholder="Dr…" maxLength={100} required /></label><label className="mt-3 block text-sm font-black">Spécialité<input value={form.specialty} onChange={(event) => setForm((value) => ({ ...value, specialty: event.target.value }))} className="field-input mt-2" placeholder="Diabétologue" /></label><div className="mt-3 grid grid-cols-2 gap-2"><label className="text-sm font-black">Date<input type="date" min={TODAY} value={form.date} onChange={(event) => setForm((value) => ({ ...value, date: event.target.value }))} className="field-input mt-2" required /></label><label className="text-sm font-black">Heure<input type="time" value={form.time} onChange={(event) => setForm((value) => ({ ...value, time: event.target.value }))} className="field-input mt-2" /></label></div><label className="mt-3 block text-sm font-black">Lieu<input value={form.location} onChange={(event) => setForm((value) => ({ ...value, location: event.target.value }))} className="field-input mt-2" /></label><div className="mt-3 grid grid-cols-2 gap-2"><label className="text-sm font-black">Répéter tous les<select value={form.recurrenceMonths} onChange={(event) => setForm((value) => ({ ...value, recurrenceMonths: event.target.value }))} className="field-input mt-2"><option value="0">Ne pas répéter</option><option value="1">1 mois</option><option value="3">3 mois</option><option value="6">6 mois</option><option value="12">12 mois</option></select></label><label className="text-sm font-black">Rappel avant<select value={form.reminderDays} onChange={(event) => setForm((value) => ({ ...value, reminderDays: event.target.value }))} className="field-input mt-2"><option value="7">1 semaine</option><option value="14">2 semaines</option><option value="30">1 mois</option></select></label></div><textarea value={form.note} onChange={(event) => setForm((value) => ({ ...value, note: event.target.value }))} className="field-input mt-3 min-h-20 py-3" placeholder="Note facultative" /><button className="mt-5 min-h-12 w-full rounded-xl bg-violet-600 font-black text-white">Enregistrer le rendez-vous</button></form></div>}
  </main>
}
