import { Minus, PackagePlus, Plus, Syringe } from 'lucide-react'
import InsulinPen from './InsulinPen'

export default function InsulinCard({ medication, todayCount, todayUnits, remainingUnits, onDecrease, onIncrease, onInject, lowStockContent, onAddToShopping }) {
  const rapid = medication.insulin === 'novorapid'
  const low = medication.stockInitialized && medication.stock <= medication.lowStockThreshold

  return <article className="relative overflow-hidden rounded-[2rem] bg-surface p-5 shadow-[0_18px_45px_rgba(15,23,42,.09)] ring-1 ring-slate-100 dark:ring-slate-800">
    <div className={`absolute -right-12 -top-14 h-36 w-36 rounded-full opacity-20 blur-2xl ${rapid ? 'bg-orange-400' : 'bg-emerald-400'}`} />
    <div className="relative flex items-center gap-4"><div className={`grid h-24 w-32 shrink-0 place-items-center overflow-hidden rounded-[1.4rem] ${rapid ? 'bg-orange-50 dark:bg-orange-950/30' : 'bg-emerald-50 dark:bg-emerald-950/30'}`}><InsulinPen type={medication.insulin} compact /></div><div className="min-w-0 flex-1"><p className={`text-xs font-black uppercase tracking-[.18em] ${rapid ? 'text-orange-500' : 'text-emerald-500'}`}>{rapid ? 'Rapide · repas' : 'Basale · quotidienne'}</p><h2 className="truncate text-2xl font-black">{medication.name}</h2><p className="mt-1 text-sm text-muted">{medication.stockInitialized ? <><strong className="text-ink">{medication.stock}</strong> stylo{medication.stock !== 1 ? 's' : ''} en stock</> : 'Stock à renseigner'}</p></div></div>
    <div className={`mt-5 h-2 overflow-hidden rounded-full ${rapid ? 'bg-orange-100 dark:bg-orange-950' : 'bg-emerald-100 dark:bg-emerald-950'}`}><div className={`h-full rounded-full ${rapid ? 'bg-gradient-to-r from-orange-500 to-rose-500' : 'bg-gradient-to-r from-emerald-500 to-teal-400'}`} style={{ width: medication.stockInitialized && medication.stock > 0 ? `${Math.min(100, Math.max(12, medication.stock * 20))}%` : '0%' }} /></div>
    <div className="mt-4 flex items-center justify-between gap-3"><div><strong className="block text-lg">{todayUnits} u aujourd’hui</strong><small className="text-muted">{todayCount} injection{todayCount !== 1 ? 's' : ''}{medication.stockInitialized ? ` · ≈ ${remainingUnits.toLocaleString('fr-FR')} u restantes` : ' · renseignez le stock'}</small></div><button type="button" onClick={onInject} className={`flex min-h-12 shrink-0 items-center gap-2 rounded-full px-5 text-sm font-black text-white shadow-lg ${rapid ? 'bg-rose-600 shadow-rose-200 dark:shadow-none' : 'bg-emerald-600 shadow-emerald-200 dark:shadow-none'}`}><Syringe size={17} /> Injecter</button></div>
    <div className="mt-4 border-t border-slate-100 pt-4 dark:border-slate-800"><div className="flex items-center justify-between"><div><strong className="block text-sm">Stylos neufs</strong><small className="text-muted">Ajuster le stock disponible</small></div><div className="flex items-center gap-2"><button type="button" onClick={onDecrease} disabled={!medication.stockInitialized || medication.stock <= 0} className="grid h-11 w-11 place-items-center rounded-xl bg-canvas disabled:opacity-30" aria-label={`Retirer un stylo ${medication.name}`}><Minus size={18} /></button><strong className="min-w-7 text-center text-xl">{medication.stockInitialized ? medication.stock : '—'}</strong><button type="button" onClick={onIncrease} className="grid h-11 w-11 place-items-center rounded-xl bg-canvas" aria-label={`Ajouter un stylo ${medication.name}`}><Plus size={18} /></button></div></div></div>
    {low && <div className="mt-4 rounded-2xl bg-amber-50 p-3 dark:bg-amber-950/30"><p className="text-xs font-black text-amber-900 dark:text-amber-200">Stock bientôt terminé</p>{lowStockContent}<button type="button" onClick={onAddToShopping} className="mt-2 flex min-h-11 w-full items-center justify-center gap-2 rounded-xl bg-amber-500 text-xs font-black text-white"><PackagePlus size={16} /> Ajouter à T9dya</button></div>}
  </article>
}
