import { Languages, LogOut, Settings2, Sparkles, Users } from 'lucide-react'
import { Link } from 'react-router-dom'
import { appRegistry } from '../registry'
import { useAuth } from '../../context/AuthContext'
import { useI18n } from '../../i18n/I18nContext'
import AppCard from './AppCard'

export default function HubPage() {
  const { household, profile, signOut } = useAuth()
  const { language, setLanguage, t } = useI18n()
  return <main className="min-h-dvh bg-canvas px-4 py-6 text-ink sm:px-6 sm:py-10"><div className="mx-auto max-w-4xl"><header className="flex items-center justify-between gap-4"><div className="flex min-w-0 items-center gap-3"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-slate-950 text-white shadow-lg dark:bg-white dark:text-slate-950"><Sparkles size={23} /></span><div className="min-w-0"><p className="text-xs font-black uppercase tracking-[0.16em] text-muted">{t('hub.kicker')}</p><h1 className="truncate text-xl font-black">{t('hub.welcome', { name: profile.displayName })}</h1></div></div><button type="button" onClick={signOut} className="grid h-11 w-11 place-items-center rounded-xl bg-surface text-muted shadow-sm" aria-label={t('hub.logout')}><LogOut size={19} /></button></header><div className="mt-5 flex items-center justify-end gap-2"><Languages size={17} className="text-muted" />{['fr', 'en', 'ar'].map((value) => <button key={value} type="button" onClick={() => setLanguage(value)} className={`min-h-10 rounded-lg px-3 text-xs font-black uppercase ${language === value ? 'bg-slate-900 text-white dark:bg-white dark:text-slate-900' : 'bg-surface text-muted'}`}>{value}</button>)}</div><section className="mt-5 overflow-hidden rounded-[2rem] bg-gradient-to-br from-slate-950 via-slate-900 to-teal-900 p-6 text-white shadow-xl sm:p-8"><div className="flex items-start justify-between gap-5"><div><p className="text-sm font-bold text-white/60">{t('hub.currentHome')}</p><h2 className="mt-2 text-3xl font-black">{household.name}</h2><p className="mt-3 flex items-center gap-2 text-sm text-white/75"><Users size={17} />{household.members?.length || 1}/2</p></div><Link to="/t9dya/settings" className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-white/10" aria-label={t('hub.settings')}><Settings2 size={22} /></Link></div></section><div className="mt-9"><p className="text-xs font-black uppercase tracking-[0.18em] text-muted">{t('hub.apps')}</p><h2 className="mt-2 text-2xl font-black">{t('hub.question')}</h2></div><section className="mt-5 grid gap-4 sm:grid-cols-2">{appRegistry.map((app) => <AppCard key={app.id} app={app} />)}</section></div></main>
}
