import { useEffect, useMemo, useState } from 'react'
import { BookHeart, Check, ChefHat, Clock3, LoaderCircle, Pencil, Plus, ShoppingBasket, Trash2, X } from 'lucide-react'
import { Link } from 'react-router-dom'
import { createCustomRecipe, deleteCustomRecipe, subscribeCustomRecipes, updateCustomRecipe } from '../../../services/cuisine'
import { addShoppingItem } from '../../../services/shopping'

const EMPTY_INGREDIENT = { name: '', quantity: '1', unit: 'pièce', emoji: '🥕' }
const EMPTY_RECIPE = { name: '', emoji: '🍲', type: 'meal', prepTime: '30', servings: '2', notes: '', steps: '', ingredients: [{ ...EMPTY_INGREDIENT }] }
const typeLabels = { meal: 'Plat', dessert: 'Dessert', juice: 'Boisson', snack: 'Snack' }
const typeGradients = { meal: 'from-orange-500 to-rose-500', dessert: 'from-fuchsia-500 to-pink-500', juice: 'from-emerald-500 to-cyan-500', snack: 'from-amber-500 to-orange-500' }

function normalizeRecipe(form) {
  return {
    name: form.name.trim(), emoji: form.emoji.trim() || '🍲', type: form.type,
    prepTime: Math.max(1, Number(form.prepTime) || 1), servings: Math.max(1, Number(form.servings) || 1),
    notes: form.notes.trim(),
    steps: form.steps.split('\n').map((step) => step.trim()).filter(Boolean).slice(0, 20),
    ingredients: form.ingredients.filter((item) => item.name.trim()).map((item, index) => ({
      id: item.id || `ingredient-${Date.now()}-${index}`,
      name: item.name.trim(), quantity: String(item.quantity || '1').trim(), unit: item.unit.trim() || 'pièce', emoji: item.emoji.trim() || '🥕'
    })).slice(0, 40)
  }
}

function RecipeEditor({ recipe, saving, onClose, onSave }) {
  const [form, setForm] = useState(() => recipe ? {
    ...recipe, prepTime: String(recipe.prepTime), servings: String(recipe.servings), steps: (recipe.steps || []).join('\n')
  } : EMPTY_RECIPE)
  const changeIngredient = (index, key, value) => setForm((current) => ({ ...current, ingredients: current.ingredients.map((item, itemIndex) => itemIndex === index ? { ...item, [key]: value } : item) }))
  const valid = form.name.trim() && form.ingredients.some((item) => item.name.trim())

  return <div className="fixed inset-0 z-[60] flex items-end justify-center sm:items-center" role="dialog" aria-modal="true"><button type="button" onClick={onClose} className="absolute inset-0 bg-slate-950/60 backdrop-blur-sm" aria-label="Fermer" /><form onSubmit={(event) => { event.preventDefault(); if (valid) onSave(normalizeRecipe(form)) }} className="relative max-h-[94dvh] w-full max-w-2xl overflow-y-auto rounded-t-[2rem] bg-canvas p-5 pb-[max(1.5rem,env(safe-area-inset-bottom))] shadow-2xl sm:rounded-[2rem] sm:p-7">
    <div className="flex items-start gap-3"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-orange-100 text-orange-700"><ChefHat /></span><div className="flex-1"><p className="text-xs font-black uppercase tracking-[.16em] text-orange-600">Carnet du foyer</p><h2 className="text-2xl font-black">{recipe ? 'Modifier la recette' : 'Inventer une recette'}</h2></div><button type="button" onClick={onClose} className="grid h-11 w-11 place-items-center rounded-full bg-surface shadow"><X /></button></div>
    <div className="mt-5 grid grid-cols-[5rem_1fr] gap-3"><label><span className="mb-2 block text-sm font-bold">Emoji</span><input value={form.emoji} onChange={(event) => setForm({ ...form, emoji: event.target.value })} className="field-input text-center text-2xl" maxLength={4} /></label><label><span className="mb-2 block text-sm font-bold">Nom du plat</span><input value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} className="field-input" placeholder="Tajine de maman…" maxLength={100} required /></label></div>
    <div className="mt-3 grid grid-cols-3 gap-3"><label><span className="mb-2 block text-sm font-bold">Type</span><select value={form.type} onChange={(event) => setForm({ ...form, type: event.target.value })} className="field-input"><option value="meal">Plat</option><option value="dessert">Dessert</option><option value="juice">Boisson</option><option value="snack">Snack</option></select></label><label><span className="mb-2 block text-sm font-bold">Minutes</span><input type="number" min="1" max="600" value={form.prepTime} onChange={(event) => setForm({ ...form, prepTime: event.target.value })} className="field-input" /></label><label><span className="mb-2 block text-sm font-bold">Personnes</span><input type="number" min="1" max="30" value={form.servings} onChange={(event) => setForm({ ...form, servings: event.target.value })} className="field-input" /></label></div>
    <div className="mt-6 flex items-center justify-between"><div><h3 className="font-black">Ingrédients</h3><p className="text-xs text-muted">Quantités gardées dans la liste de courses</p></div><button type="button" onClick={() => setForm((current) => ({ ...current, ingredients: [...current.ingredients, { ...EMPTY_INGREDIENT }] }))} className="flex min-h-10 items-center gap-2 rounded-xl bg-orange-100 px-3 text-sm font-black text-orange-700"><Plus size={17} />Ajouter</button></div>
    <div className="mt-3 space-y-3">{form.ingredients.map((ingredient, index) => <div key={ingredient.id || index} className="grid grid-cols-[3.5rem_1fr] gap-2 rounded-2xl bg-surface p-3 sm:grid-cols-[3.5rem_1fr_5rem_7rem_2.75rem]"><input aria-label="Emoji" value={ingredient.emoji} onChange={(event) => changeIngredient(index, 'emoji', event.target.value)} className="field-input px-2 text-center text-xl" maxLength={4} /><input aria-label="Ingrédient" value={ingredient.name} onChange={(event) => changeIngredient(index, 'name', event.target.value)} className="field-input" placeholder="Tomates" maxLength={80} /><input aria-label="Quantité" value={ingredient.quantity} onChange={(event) => changeIngredient(index, 'quantity', event.target.value)} className="field-input" placeholder="2" maxLength={12} /><input aria-label="Unité" value={ingredient.unit} onChange={(event) => changeIngredient(index, 'unit', event.target.value)} className="field-input" placeholder="pièces" maxLength={20} /><button type="button" onClick={() => setForm((current) => ({ ...current, ingredients: current.ingredients.filter((_, itemIndex) => itemIndex !== index) }))} disabled={form.ingredients.length === 1} className="grid h-11 w-11 place-items-center rounded-xl text-rose-600 disabled:opacity-25"><Trash2 size={18} /></button></div>)}</div>
    <label className="mt-5 block"><span className="mb-2 block text-sm font-bold">Préparation <small className="font-medium text-muted">· une étape par ligne</small></span><textarea value={form.steps} onChange={(event) => setForm({ ...form, steps: event.target.value })} className="field-input min-h-32 py-3" placeholder={'Découper les légumes\nFaire mijoter 30 minutes\nServir chaud'} maxLength={2500} /></label>
    <label className="mt-3 block"><span className="mb-2 block text-sm font-bold">Secret ou note</span><textarea value={form.notes} onChange={(event) => setForm({ ...form, notes: event.target.value })} className="field-input min-h-20 py-3" placeholder="Le petit détail qui change tout…" maxLength={600} /></label>
    <button type="submit" disabled={!valid || saving} className="mt-5 flex min-h-14 w-full items-center justify-center gap-2 rounded-2xl bg-gradient-to-r from-orange-500 to-rose-500 font-black text-white disabled:opacity-45">{saving ? <LoaderCircle className="animate-spin" /> : <BookHeart />} {saving ? 'Enregistrement…' : 'Garder dans notre carnet'}</button>
  </form></div>
}

function RecipeViewer({ recipe, lists, activeList, allItems, adding, onAdd, onEdit, onDelete, onClose }) {
  const availableLists = useMemo(() => lists.filter((list) => list.status !== 'completed'), [lists])
  const [listId, setListId] = useState(() => availableLists.find((list) => list.id === activeList?.id)?.id || availableLists[0]?.id || '')
  const [missing, setMissing] = useState([])
  const toggle = (id) => setMissing((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id])
  return <div className="fixed inset-0 z-50 flex items-end justify-center sm:items-center" role="dialog" aria-modal="true"><button type="button" onClick={onClose} className="absolute inset-0 bg-slate-950/60 backdrop-blur-sm" aria-label="Fermer" /><article className="relative max-h-[94dvh] w-full max-w-2xl overflow-y-auto rounded-t-[2rem] bg-canvas pb-[max(1.5rem,env(safe-area-inset-bottom))] shadow-2xl sm:rounded-[2rem]"><div className={`bg-gradient-to-br ${typeGradients[recipe.type]} p-6 text-white`}><div className="flex items-start"><span className="text-6xl drop-shadow">{recipe.emoji}</span><div className="ml-auto flex gap-2"><button type="button" onClick={onEdit} className="grid h-11 w-11 place-items-center rounded-full bg-white/20"><Pencil size={19} /></button><button type="button" onClick={onClose} className="grid h-11 w-11 place-items-center rounded-full bg-white/20"><X /></button></div></div><p className="mt-5 text-xs font-black uppercase tracking-[.16em] text-white/75">{typeLabels[recipe.type] || 'Recette maison'}</p><h2 className="text-3xl font-black">{recipe.name}</h2><p className="mt-2 flex gap-4 text-sm font-bold text-white/85"><span>⏱ {recipe.prepTime} min</span><span>🍽 {recipe.servings} pers.</span></p></div><div className="p-5 sm:p-7">
    <div className="flex items-end justify-between"><div><h3 className="text-lg font-black">Qu’est-ce qui manque ?</h3><p className="text-sm text-muted">Touchez seulement les ingrédients à acheter.</p></div>{missing.length > 0 && <span className="rounded-full bg-amber-100 px-3 py-1 text-xs font-black text-amber-800">{missing.length} à acheter</span>}</div>
    <div className="mt-3 grid gap-2 sm:grid-cols-2">{recipe.ingredients.map((ingredient) => { const selected = missing.includes(ingredient.id); return <button key={ingredient.id} type="button" onClick={() => toggle(ingredient.id)} className={`flex min-h-16 items-center gap-3 rounded-2xl border-2 p-3 text-left transition ${selected ? 'border-amber-400 bg-amber-50 dark:bg-amber-950/30' : 'border-transparent bg-surface'}`}><span className="text-2xl">{ingredient.emoji}</span><span className="min-w-0 flex-1"><strong className="block truncate">{ingredient.name}</strong><small className="text-muted">{ingredient.quantity} {ingredient.unit}</small></span><span className={`grid h-7 w-7 place-items-center rounded-full ${selected ? 'bg-amber-500 text-white' : 'border-2 border-slate-300'}`}>{selected && <Check size={17} />}</span></button> })}</div>
    {recipe.steps?.length > 0 && <><h3 className="mt-7 text-lg font-black">Préparation</h3><ol className="mt-3 space-y-3">{recipe.steps.map((step, index) => <li key={`${index}-${step}`} className="flex gap-3"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-orange-100 font-black text-orange-700">{index + 1}</span><p className="pt-1 text-sm leading-6">{step}</p></li>)}</ol></>}
    {recipe.notes && <p className="mt-5 rounded-2xl bg-amber-50 p-4 text-sm leading-6 text-amber-900 dark:bg-amber-950/30 dark:text-amber-200"><strong>Le secret du foyer :</strong> {recipe.notes}</p>}
    {missing.length > 0 && <div className="mt-6 rounded-2xl bg-surface p-4">{availableLists.length ? <><label className="text-sm font-bold">Envoyer vers</label><select value={listId} onChange={(event) => setListId(event.target.value)} className="field-input mt-2">{availableLists.map((list) => <option key={list.id} value={list.id}>{list.title}</option>)}</select><button type="button" disabled={!listId || adding} onClick={() => onAdd(recipe.ingredients.filter((item) => missing.includes(item.id)), listId, allItems)} className="mt-3 flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-amber-500 font-black text-white disabled:opacity-45"><ShoppingBasket size={19} />{adding ? 'Ajout en cours…' : `Ajouter ${missing.length} à la liste`}</button></> : <p className="text-sm text-muted">Créez d’abord une liste dans <Link className="font-black text-accent-700 underline" to="/t9dya/list">Mes listes</Link>.</p>}</div>}
    <button type="button" onClick={onDelete} className="mt-7 flex min-h-12 w-full items-center justify-center gap-2 rounded-xl border border-rose-200 font-black text-rose-600"><Trash2 size={18} />Supprimer cette recette</button>
  </div></article></div>
}

export default function CustomRecipeBook({ household, user, lists, activeList, allItems, notify, onBack }) {
  const [recipes, setRecipes] = useState([])
  const [loading, setLoading] = useState(true)
  const [editor, setEditor] = useState(null)
  const [selected, setSelected] = useState(null)
  const [saving, setSaving] = useState(false)
  const [adding, setAdding] = useState(false)
  useEffect(() => subscribeCustomRecipes(household.id, (data) => { setRecipes(data); setLoading(false) }, () => { setLoading(false); notify('Impossible de charger le carnet du foyer.') }), [household.id, notify])
  const save = async (recipe) => { setSaving(true); try { if (editor?.id) await updateCustomRecipe(household.id, editor.id, recipe, user.uid); else await createCustomRecipe(household.id, user.uid, recipe); setEditor(null); setSelected(null); notify(editor?.id ? 'Recette mise à jour.' : 'Nouvelle recette ajoutée au carnet.'); } catch { notify('Impossible d’enregistrer la recette.'); } finally { setSaving(false) } }
  const remove = async () => { if (!selected || !window.confirm(`Supprimer « ${selected.name} » ?`)) return; try { await deleteCustomRecipe(household.id, selected.id); setSelected(null); notify('Recette supprimée.'); } catch { notify('Impossible de supprimer la recette.'); } }
  const addMissing = async (ingredients, listId) => { setAdding(true); try { for (const ingredient of ingredients) { const productId = `recipe-${selected.id}-${ingredient.id}`; const duplicate = allItems.find((item) => item.listId === listId && item.productId === productId); const numericQuantity = Number(String(ingredient.quantity).replace(',', '.')); await addShoppingItem(household.id, listId, { id: productId, name: ingredient.name, category: 'other', categoryName: 'Recette maison', emoji: ingredient.emoji, defaultPrice: 0 }, user, { quantity: Number.isFinite(numericQuantity) && numericQuantity > 0 ? numericQuantity : 1, unit: ingredient.unit, note: `Pour ${selected.name}` }, duplicate); } notify(`${ingredients.length} ingrédient${ingredients.length > 1 ? 's ajoutés' : ' ajouté'} à la liste.`); setSelected(null); } catch { notify('Impossible d’ajouter les ingrédients à la liste.'); } finally { setAdding(false) } }
  return <section><div className="rounded-[2rem] bg-gradient-to-br from-orange-500 via-rose-500 to-fuchsia-600 p-5 text-white shadow-xl"><div className="flex items-start gap-3"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-white/20"><BookHeart /></span><div className="flex-1"><p className="text-xs font-black uppercase tracking-[.16em] text-white/75">Créé à deux</p><h2 className="text-2xl font-black">Notre carnet secret</h2><p className="mt-1 text-sm text-white/80">Vos plats, vos quantités et les petits secrets de la maison.</p></div></div><div className="mt-5 grid grid-cols-2 gap-3"><button type="button" onClick={onBack} className="min-h-12 rounded-2xl bg-white/15 font-black">← Cuisine Swipe</button><button type="button" onClick={() => setEditor({})} className="flex min-h-12 items-center justify-center gap-2 rounded-2xl bg-white font-black text-rose-600"><Plus size={19} />Nouvelle recette</button></div></div>
  {loading ? <div className="grid min-h-56 place-items-center"><LoaderCircle className="animate-spin text-orange-500" /></div> : recipes.length ? <div className="mt-5 grid gap-4 sm:grid-cols-2">{recipes.map((recipe) => <button key={recipe.id} type="button" onClick={() => setSelected(recipe)} className="overflow-hidden rounded-[1.6rem] bg-surface text-left shadow-card transition active:scale-[.98]"><div className={`bg-gradient-to-br ${typeGradients[recipe.type] || typeGradients.meal} p-5 text-white`}><span className="text-5xl">{recipe.emoji}</span><span className="float-right rounded-full bg-white/20 px-3 py-1 text-[10px] font-black uppercase">{typeLabels[recipe.type]}</span><h3 className="mt-5 text-xl font-black">{recipe.name}</h3></div><div className="flex items-center gap-4 p-4 text-xs font-bold text-muted"><span className="flex items-center gap-1"><Clock3 size={15} />{recipe.prepTime} min</span><span>{recipe.ingredients.length} ingrédients</span><span className="ml-auto text-accent-700">Ouvrir →</span></div></button>)}</div> : <div className="mt-5 rounded-[2rem] border-2 border-dashed border-orange-200 bg-orange-50/60 p-8 text-center dark:border-orange-900 dark:bg-orange-950/20"><span className="text-6xl">📖</span><h3 className="mt-4 text-xl font-black">La première page est vide</h3><p className="mt-2 text-sm leading-6 text-muted">Ajoutez votre plat signature. Il apparaîtra instantanément chez votre partenaire.</p><button type="button" onClick={() => setEditor({})} className="mt-5 min-h-12 rounded-2xl bg-orange-500 px-5 font-black text-white">Écrire notre première recette</button></div>}
  {editor && <RecipeEditor recipe={editor.id ? editor : null} saving={saving} onClose={() => setEditor(null)} onSave={save} />}
  {selected && <RecipeViewer recipe={selected} lists={lists} activeList={activeList} allItems={allItems} adding={adding} onAdd={addMissing} onEdit={() => { setEditor(selected); setSelected(null) }} onDelete={remove} onClose={() => setSelected(null)} />}
  </section>
}
