import { useEffect, useMemo, useState } from 'react'
import { Check, Clock3, ShoppingCart, X } from 'lucide-react'
import { Link } from 'react-router-dom'
import SmartImage from './SmartImage'

export default function RecipeDetail({ recipe, ingredientsById, lists, activeList, onClose, onAddMissing, adding }) {
  const availableLists = useMemo(() => lists.filter((list) => list.status !== 'completed'), [lists])
  const initialListId = availableLists.length === 1 ? availableLists[0].id : (availableLists.some((list) => list.id === activeList?.id) ? activeList.id : '')
  const [listId, setListId] = useState(initialListId)

  useEffect(() => {
    const close = (event) => { if (event.key === 'Escape') onClose() }
    window.addEventListener('keydown', close)
    return () => window.removeEventListener('keydown', close)
  }, [onClose])

  return <div className="fixed inset-0 z-50 flex items-end justify-center sm:items-center" role="dialog" aria-modal="true" aria-labelledby="recipe-title"><button type="button" onClick={onClose} className="absolute inset-0 bg-slate-950/55 backdrop-blur-sm" aria-label="Fermer la recette" /><article className="relative max-h-[92dvh] w-full max-w-2xl overflow-y-auto rounded-t-[2rem] bg-canvas pb-[max(1.5rem,env(safe-area-inset-bottom))] shadow-2xl sm:rounded-[2rem]"><SmartImage src={recipe.imageUrl} alt={recipe.name_fr} className="h-64 w-full sm:h-72" /><button type="button" onClick={onClose} className="absolute right-4 top-4 grid h-11 w-11 place-items-center rounded-full bg-white/90 text-slate-900 shadow" aria-label="Fermer"><X /></button><div className="p-5 sm:p-7"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-extrabold uppercase tracking-[0.16em] text-accent-700">{recipe.origin}</p><h2 id="recipe-title" className="mt-1 text-2xl font-black sm:text-3xl">{recipe.name_fr}</h2>{recipe.name_darija && <p className="text-muted">{recipe.name_darija}</p>}</div><span className="rounded-xl bg-emerald-100 px-3 py-2 font-black text-emerald-700 dark:bg-emerald-950/50 dark:text-emerald-300">{recipe.matchPercent}%</span></div><p className="mt-3 flex items-center gap-2 text-sm font-semibold text-muted"><Clock3 size={17} /> {recipe.prepTime} min · {recipe.difficulty}</p>
      <h3 className="mt-6 text-lg font-black">Ingrédients</h3><div className="mt-3 grid gap-2 sm:grid-cols-2">{recipe.ingredients.map(({ ingredientId, required }) => { const ingredient = ingredientsById[ingredientId]; const missing = recipe.missingIngredients.some((item) => item.id === ingredientId); return <div key={ingredientId} className={`flex items-center gap-3 rounded-xl p-3 ${missing ? 'bg-amber-50 text-amber-900 dark:bg-amber-950/30 dark:text-amber-200' : 'bg-surface'}`}><span className="text-2xl">{ingredient?.emoji || '🥄'}</span><span className="min-w-0 flex-1"><strong className="block">{ingredient?.name_fr || ingredientId}</strong><small>{required ? 'Nécessaire' : 'Optionnel'}</small></span>{!missing && <Check size={18} className="text-emerald-500" />}</div> })}</div>
      <h3 className="mt-6 text-lg font-black">Préparation</h3><ol className="mt-3 space-y-3">{recipe.steps.map((step, index) => <li key={step} className="flex gap-3"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-accent-100 font-black text-accent-700 dark:bg-accent-950">{index + 1}</span><p className="pt-1 text-sm leading-6">{step}</p></li>)}</ol>
      {recipe.missingIngredients.length > 0 && <div className="mt-7 rounded-2xl bg-surface p-4 shadow-sm"><h3 className="font-black">Ajouter ce qui manque</h3>{availableLists.length ? <><label className="mt-3 block text-sm font-bold" htmlFor="recipe-list">Liste de courses</label><select id="recipe-list" value={listId} onChange={(event) => setListId(event.target.value)} className="mt-1 h-12 w-full rounded-xl border border-slate-200 bg-canvas px-3 dark:border-slate-700">{availableLists.length > 1 && <option value="">Choisir une liste…</option>}{availableLists.map((list) => <option key={list.id} value={list.id}>{list.title}</option>)}</select><button type="button" disabled={!listId || adding} onClick={() => onAddMissing(recipe, listId)} className="mt-3 flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-accent-600 px-4 font-extrabold text-white disabled:opacity-45"><ShoppingCart size={19} /> {adding ? 'Ajout en cours…' : `Ajouter ${recipe.missingIngredients.length} ingrédient${recipe.missingIngredients.length > 1 ? 's' : ''}`}</button></> : <div className="mt-3 rounded-xl bg-amber-50 p-3 text-sm text-amber-900 dark:bg-amber-950/30 dark:text-amber-200">Crée d’abord une liste depuis <Link to="/t9dya/list" className="font-black underline">Mes listes</Link>. Aucune liste ne sera créée automatiquement.</div>}</div>}
    </div></article></div>
}
