import { AnimatePresence, motion as Motion, useReducedMotion } from 'framer-motion'
import { CheckCircle2, ChevronRight, Clock3, RotateCcw, ShoppingCart } from 'lucide-react'
import SmartImage from './SmartImage'

function RecipeCard({ recipe, onOpen, index, reduced }) {
  return <Motion.button type="button" onClick={() => onOpen(recipe)} initial={reduced ? false : { opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: Math.min(index * 0.055, 0.35) }} className="w-full overflow-hidden rounded-[1.6rem] bg-surface text-left shadow-sm ring-1 ring-slate-200/70 transition hover:-translate-y-0.5 hover:shadow-md dark:ring-slate-700"><div className="flex min-h-36"><SmartImage src={recipe.imageUrl} alt={recipe.name_fr} className="w-32 shrink-0 sm:w-44" /><span className="flex min-w-0 flex-1 flex-col p-4"><span className="flex items-start justify-between gap-2"><span className={`rounded-full px-2.5 py-1 text-xs font-black ${recipe.readiness === 'ready' ? 'bg-emerald-100 text-emerald-700 dark:bg-emerald-950/60 dark:text-emerald-300' : 'bg-amber-100 text-amber-700 dark:bg-amber-950/60 dark:text-amber-300'}`}>{recipe.readiness === 'ready' ? 'Prêt à cuisiner' : `${recipe.missingIngredients.length} manque${recipe.missingIngredients.length > 1 ? 'nt' : ''}`}</span><strong className="text-accent-700">{recipe.matchPercent}%</strong></span><strong className="mt-2 line-clamp-2 text-lg font-black">{recipe.name_fr}</strong><span className="mt-auto flex items-center gap-3 pt-2 text-xs font-semibold text-muted"><span className="flex items-center gap-1"><Clock3 size={14} /> {recipe.prepTime} min</span><span>{recipe.difficulty}</span><ChevronRight className="ml-auto" size={17} /></span></span></div></Motion.button>
}

export default function ResultsList({ results, onOpen, onRestart, onChangeCategory }) {
  const reduced = useReducedMotion()
  const ready = results.filter((recipe) => recipe.readiness === 'ready')
  const almost = results.filter((recipe) => recipe.readiness === 'almost')
  const ideas = results.filter((recipe) => recipe.readiness === 'partial')
  return <section aria-labelledby="results-title"><div className="mb-5 rounded-[1.75rem] bg-gradient-to-br from-accent-600 to-emerald-500 p-5 text-white shadow-lg"><p className="text-xs font-extrabold uppercase tracking-[0.18em] text-white/75">Étape 3 sur 3</p><h2 id="results-title" className="mt-1 text-2xl font-black">Voilà ce qu’on peut préparer</h2><p className="mt-1 text-sm text-white/80">{ready.length} recette{ready.length !== 1 ? 's' : ''} prête{ready.length !== 1 ? 's' : ''} · {almost.length} presque prête{almost.length !== 1 ? 's' : ''}</p></div>
    {!ready.length && !almost.length && <div className="rounded-[1.75rem] border border-dashed border-slate-300 bg-surface p-8 text-center dark:border-slate-700"><span className="text-5xl">🧺</span><h3 className="mt-3 text-xl font-black">Pas encore assez d’ingrédients</h3><p className="mt-1 text-sm text-muted">Refais un passage ou choisis une autre catégorie.</p></div>}
    <AnimatePresence>{ready.length > 0 && <div className="mb-7"><h3 className="mb-3 flex items-center gap-2 text-lg font-black"><CheckCircle2 className="text-emerald-500" /> Prêt à cuisiner</h3><div className="grid gap-3">{ready.map((recipe, index) => <RecipeCard key={recipe.id} recipe={recipe} onOpen={onOpen} index={index} reduced={reduced} />)}</div></div>}</AnimatePresence>
    {almost.length > 0 && <div><h3 className="mb-3 flex items-center gap-2 text-lg font-black"><ShoppingCart className="text-amber-500" /> Presque prêt</h3><div className="grid gap-3">{almost.map((recipe, index) => <RecipeCard key={recipe.id} recipe={recipe} onOpen={onOpen} index={index} reduced={reduced} />)}</div></div>}
    {ideas.length > 0 && <div className="mt-7"><h3 className="mb-1 text-lg font-black">Bonnes pistes</h3><p className="mb-3 text-sm text-muted">Au moins 60 % des ingrédients sont déjà là.</p><div className="grid gap-3">{ideas.map((recipe, index) => <RecipeCard key={recipe.id} recipe={recipe} onOpen={onOpen} index={index} reduced={reduced} />)}</div></div>}
    <div className="mt-7 grid grid-cols-2 gap-3"><button type="button" onClick={onRestart} className="flex min-h-12 items-center justify-center gap-2 rounded-2xl bg-surface font-bold shadow-sm"><RotateCcw size={18} /> Recommencer</button><button type="button" onClick={onChangeCategory} className="min-h-12 rounded-2xl bg-slate-900 px-3 font-bold text-white dark:bg-white dark:text-slate-900">Changer d’envie</button></div>
  </section>
}
